### ISSUE TITLE
Bug: answer box is stuck at last answer

### ISSUE THREAD

**Issue by Evevon** [wkdonc/wkdonc.github.io#3]
First of all: Great tool, I love it! Sadly I did encounter a small bug while using it:

When using the conjugator for na-adjectives, the answer from a previous question will still show and it is impossible to give a new answer.

Reproduce bug: select 'na-adjectives' as option and answer a few questions to run into this problem.

Console will throw the following error:
```
Uncaught TypeError: dictionary.replace is not a function
    at generateQuestion (drill.js:427)
    at proceed (drill.js:614)
    at HTMLButtonElement.onclick (drill.html:235)
```
It seems like line 427 from drill.js is attempting to use the string replace function on an array.

**Comment by wkdonc** [comment]
This bug has just been fixed. Thanks for the report.
